// Generates the Prisma client after `npm install`.
//
// The Prisma CLI is a development tool: the running API needs only `@prisma/client` and the driver
// adapter. A production install (`--omit=dev`, as the Mac app's build does) leaves the CLI out, so
// there the client must already have been generated by whatever staged the files — and if it was
// not, say so now rather than at the first request.
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const here = path.resolve(import.meta.dirname, "..");
const generated = path.join(here, "src/generated/prisma/client.ts");
const require = createRequire(import.meta.url);

let cli = null;
try {
  cli = require.resolve("prisma/build/index.js");
} catch {
  cli = null;
}

if (cli) {
  const run = spawnSync(process.execPath, [cli, "generate"], { cwd: here, stdio: "inherit" });
  process.exit(run.status ?? 1);
}
if (existsSync(generated)) {
  console.log("prisma CLI not installed (production install); using the client generated at build time");
  process.exit(0);
}
console.error("The Prisma client has not been generated and the CLI is not installed to generate it.");
process.exit(1);
